#!/bin/bash

# Scripts útiles para mantenimiento del sistema SAEM

echo "🔧 Scripts de Mantenimiento - Seguimiento SAEM"
echo "==============================================="
echo ""
echo "Comandos disponibles:"
echo ""
echo "📊 MONITOREO:"
echo "  pm2 status                     # Ver estado de la aplicación"
echo "  pm2 logs seguimiento-saem      # Ver logs en tiempo real"
echo "  pm2 monit                      # Monitor gráfico de PM2"
echo "  tail -f /home/ubuntu/seguimiento/logs/health-check.log  # Ver logs de monitoreo"
echo ""
echo "🔄 REINICIO:"
echo "  pm2 restart seguimiento-saem   # Reiniciar aplicación"
echo "  pm2 reload seguimiento-saem    # Reinicio sin downtime"
echo "  sudo systemctl restart nginx  # Reiniciar nginx"
echo ""
echo "🔍 DIAGNÓSTICO:"
echo "  curl -I http://localhost:3000                    # Probar Next.js directamente"
echo "  curl -I -k https://seguimiento.saem.gob.mx      # Probar sitio completo"
echo "  sudo tail -20 /var/log/nginx/error.log          # Ver errores de nginx"
echo "  pm2 describe seguimiento-saem                    # Detalles de la aplicación"
echo ""
echo "⚙️ CONFIGURACIÓN CRONTAB (monitoreo cada 5 min):"
echo "  */5 * * * * /home/ubuntu/seguimiento/monitor-health.sh"
echo ""
echo "🚨 EN CASO DE EMERGENCIA:"
echo "  ./emergency-restart.sh         # Reinicio completo del sistema"
echo ""
